name: MERN CI

on:
  push:
    branches: [main]

jobs:
  mongo-init:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Waiting for MongoDB to be ready
        run: |
          until nc -z localhost 27017; do
            echo "waiting for MongoDB...."
            sleep 2
          done
          echo "MongoDB is up"

      - name: Seed MongoDB
        working-directory: ./backend
        run: |
          npm install
          node seedTaskData.js  # make sure filename is correct

  test:
    runs-on: ubuntu-latest
    needs: mongo-init

    env:
      PORT: 5000
      MONGO_URI: mongodb://localhost:27017/mern_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        run: npm test
