name: MERN CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      PORT: 5000
      MONGO_URI: mongodb://localhost:27017/mern_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Seed MongoDB
        working-directory: ./backend
        run: node seedTasksData.js  # adjust if file name differs

      - name: Run backend tests
        working-directory: ./backend
        run: npm test
